/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barestoque.view.telas.fornecedor;

import barestoque.DAO.FornecedorDAO;
import barestoque.controller.ControladorCadastroLista;
import barestoque.model.Fornecedor;
import barestoque.view.InicializadorLookAndFeel;
import barestoque.view.componentes.TabelaModelo;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nolas
 */
public class ListaFornecedor extends javax.swing.JPanel {

    /**
     * Creates new form ListaFornecedor
     */
    public ListaFornecedor() {
        initComponents();
        setBackground(InicializadorLookAndFeel.COR_FOREGROUND);
        
        atualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFornecedor = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Fornecedores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tabelaFornecedor.setBorder(new javax.swing.border.StrokeBorder(new java.awt.BasicStroke (1f), InicializadorLookAndFeel.COR_BACKGROUND));
        tabelaFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "codigo", "nome", "telefone", "CNPJ"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tabelaFornecedor.setFillsViewportHeight(true);
        tabelaFornecedor.setRowHeight(28);
        jScrollPane1.setViewportView(tabelaFornecedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JTable getTabelaFornecedor() {
        return tabelaFornecedor;
    }
    
    public void atualizar ()
    {
        TabelaModelo tabelaModelo = new TabelaModelo();
        tabelaModelo.addColumn("Codigo");
        tabelaModelo.addColumn("Nome");
        tabelaModelo.addColumn("Telefone");
        tabelaModelo.addColumn("CNPJ");
        
        
        FornecedorDAO fdao = new FornecedorDAO();
        ArrayList <Fornecedor> listaFornecedor = fdao.listaDeFornecedores();
        for (Fornecedor f : listaFornecedor)
            tabelaModelo.addRow(fdao.desmontarParaLista(f));
        
        tabelaFornecedor.setModel(tabelaModelo);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaFornecedor;
    // End of variables declaration//GEN-END:variables
}
